import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { unitRepository } from '../../../core/repositories/UnitRepository';
import { Unit as ModelUnit } from '../../../types/models';
export type Unit = ModelUnit & { shortName?: string; status?: string };
export const UNIT_QUERY_KEY = ['units'] as const;
const view = (item: ModelUnit): Unit => ({ ...item, shortName: item.abbreviation, status: 'Active' });
export const useUnits = () => { const client = useQueryClient(); return useQuery({ queryKey: UNIT_QUERY_KEY, queryFn: async () => { const local = (await unitRepository.getAll()).map(view); void unitRepository.fetchFromApi().then(() => unitRepository.getAll().then(items => client.setQueryData(UNIT_QUERY_KEY, items.map(view)))); return local; } }); };
export const useAddUnit = () => { const client = useQueryClient(); return useMutation({ mutationFn: async (data: Partial<Unit>) => { const item = { ...data, abbreviation: data.abbreviation || data.shortName || '', id: data.id || Math.floor(Math.random() * -1000000000), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), syncStatus: 'pending_insert' as const } as ModelUnit; await unitRepository.insert(item); return view(item); }, onSuccess: item => { client.setQueryData(UNIT_QUERY_KEY, (old: Unit[] | undefined) => [...(old || []), item]); client.invalidateQueries({ queryKey: UNIT_QUERY_KEY, refetchType: 'none' }); } }); };
export const useUpdateUnit = () => { const client = useQueryClient(); return useMutation({ mutationFn: async (data: Unit) => { const item = { ...data, abbreviation: data.abbreviation || data.shortName || '', updatedAt: new Date().toISOString(), syncStatus: 'pending_update' as const } as ModelUnit; await unitRepository.update(item); return view(item); }, onSuccess: item => { client.setQueryData(UNIT_QUERY_KEY, (old: Unit[] | undefined) => (old || []).map(row => row.id === item.id ? item : row)); client.invalidateQueries({ queryKey: UNIT_QUERY_KEY, refetchType: 'none' }); } }); };
export const useDeleteUnit = () => { const client = useQueryClient(); return useMutation({ mutationFn: async (id: number) => { await unitRepository.delete(id); return id; }, onSuccess: id => { client.setQueryData(UNIT_QUERY_KEY, (old: Unit[] | undefined) => (old || []).filter(row => row.id !== id)); client.invalidateQueries({ queryKey: UNIT_QUERY_KEY, refetchType: 'none' }); } }); };


